apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-scraper-mcp
  labels:
    app: job-scraper-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-scraper-mcp
  template:
    metadata:
      labels:
        app: job-scraper-mcp
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - dta32-homeserver
      containers:
        - name: job-scraper-mcp
          image: dta32/job-scrapper-orangemangodimz-mcp:v1.0.2 # or replacedbycicd
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: job-scraper-config
            - secretRef:
                name: job-scraper-secret
